<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.seckill</groupId><artifactId>ticket-seckill</artifactId><version>1.0.0</version></parent><artifactId>application</artifactId><dependencies><dependency><groupId>com.seckill</groupId><artifactId>common</artifactId><version>${project.version}</version></dependency><dependency><groupId>com.seckill</groupId><artifactId>infrastructure</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.apache.rocketmq</groupId><artifactId>rocketmq-spring-boot-starter</artifactId><version>${rocketmq.version}</version></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-aop</artifactId></dependency></dependencies></project>
